### ISSUE TITLE
[疑问] 自定义图形注册以后，当前画布销毁，在当前页面再次实列化topology并再次注册自定义图形发现图形背景色不显示了

### ISSUE THREAD

**Issue by hsbtr** [le5le-com/meta2d.js#104]
```
const baseBusBar = (pen, ctx) => {
  const path = !ctx ? new Path2D() : ctx;
  const { x, y, width, height } = pen.calculative.worldRect;
  path.moveTo(x, y);
  path.lineTo(x + width, y); // 上
  path.lineTo(x + width, y + height); // 右
  path.lineTo(x, y + height); // 下
  path.lineTo(x, y); //左
  path.closePath();
  if (path instanceof Path2D) return path;
}
```

因为业务中需要用tabs实现多个图纸，限定只实列化当前选中得tab其余得画布都会销毁，然后发现只有第一个tab才能显示这个自定义图形，其他tab里自定义图形背景色填充都失效了

![image](https://user-images.githubusercontent.com/46487804/186193717-878338e2-1599-41c8-807c-0dfe2035f636.png)

**Comment by hsbtr** [comment]
补上重现[demo](https://github.com/hsbtr/reproduce-topology-scenes.git)； 推测销毁画布后未将window上topology某些数据清空

**Comment by SignDawn** [comment]
看了下你的 demo ，问题出现在旧版本中，推荐升级到最新的 1.2.16 。
并且在销毁时，参数传 true ，已测试
topologyRef.current?.destroy(true);
![image](https://user-images.githubusercontent.com/48878568/211206876-82935477-2762-4227-b708-594d7b26ff46.png)

**Comment by SignDawn** [comment]
下回发 demo ，可以使用 codesandbox
