### ISSUE TITLE
Shift 快捷键 异常

### ISSUE THREAD

**Issue by Blizzard-liu** [le5le-com/meta2d.js#109]
![11](https://user-images.githubusercontent.com/20244432/187168499-bdadbd86-41a6-460c-a399-5d0296db90b2.gif)
![1661764623116](https://user-images.githubusercontent.com/20244432/187168535-049bb40a-65e1-48fc-88de-3f089c450ed6.png)

**Comment by SignDawn** [comment]
这个已经修复了。
可以在官方尝试
