### ISSUE TITLE
[建议] 支持 line jump

### ISSUE THREAD

**Issue by jshenguru** [le5le-com/meta2d.js#115]
能否支持类似 draw.io 中的 line jump 功能？当线条交叉时，在交叉处跳线。

有了这个功能，topology.js 真的秒杀 draw.io 

![Screenshot_2022-09-04_19-22-32](https://user-images.githubusercontent.com/26332171/188337486-4ee7450d-cbda-478b-a5a7-6ea52ab3bb63.png)

**Comment by ForestHo** [comment]
![47d32d68242aa41d18f49bf021a1133](https://user-images.githubusercontent.com/16076805/193211722-8c4790a5-0b8b-46b2-8ae1-9f5b35081829.jpg)
支持line jump，企业付费功能，有意向的话，联系我们商务
![image](https://user-images.githubusercontent.com/16076805/193211967-8aa08db4-04b1-45fa-aec5-d14ded07a8ef.png)

**Comment by jshenguru** [comment]
> ![47d32d68242aa41d18f49bf021a1133](https://user-images.githubusercontent.com/16076805/193211722-8c4790a5-0b8b-46b2-8ae1-9f5b35081829.jpg) 支持line jump，企业付费功能，有意向的话，联系我们商务[business@le5le.com](mailto:business@le5le.com), 微信: qinaa66
> 
> > 能否支持类似 draw.io 中的 line jump 功能？当线条交叉时，在交叉处跳线。
> > 有了这个功能，topology.js 真的秒杀 draw.io
> > ![Screenshot_2022-09-04_19-22-32](https://user-images.githubusercontent.com/26332171/188337486-4ee7450d-cbda-478b-a5a7-6ea52ab3bb63.png)

个人觉得这是个基本功能，把它放到企业付费功能中有些难以接受。

**Comment by ForestHo** [comment]
> > ![47d32d68242aa41d18f49bf021a1133](https://user-images.githubusercontent.com/16076805/193211722-8c4790a5-0b8b-46b2-8ae1-9f5b35081829.jpg) 支持line jump，企业付费功能，有意向的话，联系我们商务[business@le5le.com](mailto:business@le5le.com), 微信: qinaa66
> > > 能否支持类似 draw.io 中的 line jump 功能？当线条交叉时，在交叉处跳线。
> > > 有了这个功能，topology.js 真的秒杀 draw.io
> > > ![Screenshot_2022-09-04_19-22-32](https://user-images.githubusercontent.com/26332171/188337486-4ee7450d-cbda-478b-a5a7-6ea52ab3bb63.png)
> 
> 个人觉得这是个基本功能，把它放到企业付费功能中有些难以接受。

初创企业，小成本运营，这个定制功能前后花了8~10天才完全完成，人力成本和时间成本都是需要的，如果不想付费就自己写算法实现。
