### ISSUE TITLE
valueUpdate不执行的问题

### ISSUE THREAD

**Issue by SHEE94** [le5le-com/meta2d.js#125]
![image](https://user-images.githubusercontent.com/29197247/202979624-b45b349f-2460-489d-acd9-51105644103a.png)
添加事件类型valueUpdate无法触发

**Comment by SignDawn** [comment]
锁定画布了嘛？
给个 codesandbox 或者 官网的录屏吧

**Comment by Alsmile** [comment]
请补充信息后重开
