### ISSUE TITLE
【建议】Text组件弱化width的属性，根据文字的字号和文字多少自动适应长度

### ISSUE THREAD

**Issue by wang11111** [le5le-com/meta2d.js#13]
只有点击边框部分才能选择，较长的时候文字也无法选中（也可以通过调整长宽来，如果自动设置好，是不是更方便）
![image](https://user-images.githubusercontent.com/14358013/156508761-cb6fe1e8-f115-4c7f-ac5e-79464733ff0d.png)

**Comment by ananzhusen** [comment]
1.0.24 版本后，新增属性 https://doc.le5le.com/document/119895613#textAutoAdjust
