### ISSUE TITLE
连续点等距分布，上下对齐时，会出现组件上下方向不断移动BUG

### ISSUE THREAD

**Issue by jslc2008** [le5le-com/meta2d.js#130]
拖出三个一样的控件，将其中一个控件缩小，然后全部选中。连续点等距分布，上下对齐时，会出现控件上下逐渐向下偏移的情况
当三个控件一样大小时，不会出现上述问题

**Comment by ananzhusen** [comment]
官网测试没发现这个问题，最好提供下操作视频

**Comment by Blizzard-liu** [comment]
https://user-images.githubusercontent.com/20244432/236359260-82e3da8e-63e7-48ab-a74a-53cc3ed22065.mp4

我也遇到过 应该是这个问题
