### ISSUE TITLE
建议提供 Ctrl + S 快捷键保存画布的功能

### ISSUE THREAD

**Issue by jslc2008** [le5le-com/meta2d.js#131]
画布最好增加 Ctrl + S 快捷键保存画布的功能

**Comment by SignDawn** [comment]
你是用户还是开发者？
开发者的话，建议自行去监听 键盘 事件，因为保存后的行为，是保存后端，还是保存 localStorage ？自行开发可控性更高，如果 库 来实现的话，无非只是帮你多套一层而已。

**Comment by jslc2008** [comment]
我只是用户，感觉你们这个做点的还是挺好的，拿来画画图

**Comment by SignDawn** [comment]
https://codesandbox.io/s/adoring-neco-u44l1u?file=/src/App.js
示例，抽空看下要不要加

**Comment by jslc2008** [comment]
好的， 谢谢

**Comment by SignDawn** [comment]
https://github.com/le5le-com/meta2d.js/pull/134

**Comment by SignDawn** [comment]
https://2d.le5le.com/
