### ISSUE TITLE
下载下来的图片不显示背景图

### ISSUE THREAD

**Issue by zhang-jianxun** [le5le-com/meta2d.js#136]
meta2d.setBackgroundImage(
      'https://t7.baidu.com/it/u=1595072465,3644073269&fm=193&f=GIF',
    );
meta2d.downloadPng();

下载下来的图片不显示背景图。

**Comment by SignDawn** [comment]
因为加载图片是耗时的。
现在来看，只能在执行 downloadPng 时加个定时器。
meta2d.setBackgroundImage(
'https://t7.baidu.com/it/u=1595072465,3644073269&fm=193&f=GIF',
);
    setTimeout(() => {
      meta2d.downloadPng();
    }, 1000);

**Comment by SignDawn** [comment]
下个版本，考虑把上面  setBackgroundImage 变成一个异步方法，可用 await 等待

**Comment by SignDawn** [comment]
还有跨域问题，等下个版本吧。
未来使用方式：
await meta2d.setBackgroundImage(
    'https://t7.baidu.com/it/u=1595072465,3644073269&fm=193&f=GIF',
    );
   // console.log(meta2d.store.bkImg)
    meta2d.downloadPng()

**Comment by SignDawn** [comment]
https://github.com/le5le-com/meta2d.js/pull/135

**Comment by SignDawn** [comment]
源码里已经修复了
