### ISSUE TITLE
能否提供下载为 svg 的接口

### ISSUE THREAD

**Issue by ZCY1715** [le5le-com/meta2d.js#137]
在文档中只有 downloadPng

**Comment by ZCY1715** [comment]
我在做导师的课题任务，需要将流程图导出为 svg 的功能，也不需要非常理想的效果，我可以使用 adobe illustrator 矢量图工具进行路径描摩后再编辑

**Comment by SignDawn** [comment]
可以加官方群问问

**Comment by SignDawn** [comment]
https://github.com/le5le-com/meta2d.js/pull/199
