### ISSUE TITLE
建议增加一个 afterRender 监听函数

### ISSUE THREAD

**Issue by ZCY1715** [le5le-com/meta2d.js#138]
现在只能自己实现

```js
// 函数监听
function onFunction(obj, fnName, callback) {
  const _fn = obj[fnName]
  obj[fnName] = function (...args) {
    _fn.apply(obj, args)
    callback()
  }
}

onFunction(meta2d, "render", () => {
    const isActive= meta2d.store.active.length !== 0
    if (isActive) {
      meta2d.emit("updateElement")
    }
})
```

**Comment by ZCY1715** [comment]
文档中没有对画布中是否有元素正处于active的监听，我在vue中 watch meta2d.store.active.length 总是失败，经过分析是因为每次画布中活动元素变化后都是将 store.active 对象用新的active对象替换掉，因此我的属性面板组件不知道在什么时候呈现画布设置还是画笔设置的状态。同时我还想针对 line、pen、line与pen的混合，在属性面板显示不同的设置选项。我想将这个判断放在每次画布出现变化后，也就是 render 后一刻。

可能出现active变化以及active中种类变化的情况有 手动在画布区域操作，从元件库中拉取，复制、粘贴、剪贴、删除、redo、undo等等，这些都会触发 render 函数

**Comment by ZCY1715** [comment]
文档中没有对画布中是否有元素正处于active的监听，我在vue中 watch meta2d.store.active.length 总是失败，经过分析是因为每次画布中活动元素变化后都是将 store.active 对象用新的active对象替换掉，因此我的属性面板组件不知道在什么时候呈现画布设置还是画笔设置的状态。同时我还想针对 line、pen、line与pen的混合，在属性面板显示不同的设置选项。我想将这个判断放在每次画布出现变化后，也就是 render 后一刻。

可能出现active变化以及active中种类变化的情况有 手动在画布区域操作，从元件库中拉取，复制、粘贴、剪贴、删除、redo、undo等等，这些都会触发 render 函数

**Comment by SignDawn** [comment]
vue watch 只能监听一个 vue 配置好的响应式对象，其它的肯定监听不到啊。
发布订阅有了解吗？
meta2d.on('active', () => {})
https://developer.le5le.com/tutorial/events.html#%E5%86%85%E7%BD%AE-api-%E6%B6%88%E6%81%AF
你想要的应该是这个文档，看看

**Comment by ZCY1715** [comment]
哦哦哦，明白了，我就是需要这个

**Comment by ZCY1715** [comment]
那我发现了一个文档的 bug

![image](https://user-images.githubusercontent.com/75206433/220649187-ad3454c0-4728-45fb-a719-826ee580370e.png)
![image](https://user-images.githubusercontent.com/75206433/220649285-911d6189-474f-4449-9263-0b485cfb0b2c.png)
![image](https://user-images.githubusercontent.com/75206433/220649350-e0821d7d-b167-4a71-8c51-60723544ab26.png)

我从上一个菜单项点击到消息事件时，会没有内容，只有在消息事件选项时刷新，或直接 url 进入才有内容

**Comment by ZCY1715** [comment]
此前我一直以为这部分文档没有做完呢。。。

**Comment by SignDawn** [comment]
这文档的 bug ，还不清楚原因。
问题解决了， close 了

**Comment by ZCY1715** [comment]
> vue watch 只能监听一个 vue 配置好的响应式对象，其它的肯定监听不到啊。 发布订阅有了解吗？ meta2d.on('active', () => {}) https://developer.le5le.com/tutorial/events.html#%E5%86%85%E7%BD%AE-api-%E6%B6%88%E6%81%AF 你想要的应该是这个文档，看看

对于您说的这个问题，我是将 meta2d 对象放在 pinia Store 中的，使用时:
```js
const {meta2d} = storeToRefs(meta2dStore)

watch(() => meta2d.value.store.active.length, () => {
    // todo
})

```

按理说应该是能监听到的

**Comment by Plortinus** [comment]
可以这样设置监听
``` js
  const meta2d = new Meta2d('editor-meta2d', {
    grid: true,
    rule: true,
  })
  this.meta2dObs = Vue.observable({ meta2d })
```
meta2dObs就是一个响应式的对象了,this.meta2dObs.meta2d就是meta2d对象
