### ISSUE TITLE
Win系统启动APP.EXE后访问地址报错

### ISSUE THREAD

**Issue by include0000** [le5le-com/meta2d.js#139]
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by include0000** [comment]
在Win10系统下  mongodb正确安装并修改了配置文件。启动APP.EXE后显示服务已经启动。

**Comment by ananzhusen** [comment]
最新的拉下来再试试
