### ISSUE TITLE
开源版本example跑起来后似乎组件内容很少

### ISSUE THREAD

**Issue by Mrjing** [le5le-com/meta2d.js#142]
![image](https://user-images.githubusercontent.com/16788862/223894979-3ca61b65-531a-40ab-b201-c27ad4a36068.png)

![image](https://user-images.githubusercontent.com/16788862/223895103-46726887-1999-4fe9-8c84-4faaa6725c94.png)
看源码是有不少组件的，是没有build到产物里吗

**Comment by ananzhusen** [comment]
官方文档里的例子里只有基本形状，其他图形库需要单独注册

**Comment by Mrjing** [comment]
好的，谢谢
