### ISSUE TITLE
麻烦问下如何在这个拖拽事件里自定义组合图形数据呢？

### ISSUE THREAD

**Issue by xiaohouzi007** [le5le-com/meta2d.js#143]
![0734982bfd07f391e6e1eda0b3340e2](https://user-images.githubusercontent.com/32658842/224211415-6765ad35-d100-463c-9559-17d41089c1c3.png)
想自定义一个包含矩形、线、多边形等多个基础图形组合而成的图形，然后拖拽添加至画布里

**Comment by SignDawn** [comment]
https://developer.le5le.com/api/core.html#combine

**Comment by xiaohouzi007** [comment]
这个方法返回空呀，setData里如何赋值呢

**Comment by xiaohouzi007** [comment]
> https://developer.le5le.com/api/core.html#combine
这个方法返回空呀，setData里如何赋值呢

**Comment by SignDawn** [comment]
https://developer.le5le.com/api/core.html#tocomponent
返回值就是的
