### ISSUE TITLE
polyline连线时 会在前方元素后 和 后方元素前 生成一个无意义锚点

### ISSUE THREAD

**Issue by zzw0118** [le5le-com/meta2d.js#145]
![image](https://user-images.githubusercontent.com/45869191/224929323-168c19a2-b96a-4a35-b28e-f5645dcbe891.png)
如图 这两个锚点没有操作意义, 在锁定连线不可拖动时还能在x轴拖动,导致连线展示异常

**Comment by SignDawn** [comment]
![image](https://user-images.githubusercontent.com/48878568/224995224-d473a2d9-4c93-4d44-988b-e0d8459b5a31.png)
这个点是为了应对这种情况的，最小的拐点。
