### ISSUE TITLE
麻烦问下基础图元里有多边形吗？就是能根据提供的坐标点，自动绘制多边形

### ISSUE THREAD

**Issue by xiaohouzi007** [le5le-com/meta2d.js#148]
麻烦问下基础图元里有多边形吗？就是能根据提供的坐标点，自动绘制多边形，多边形可能是不规则的

**Comment by SignDawn** [comment]
没有，可以自己实现，也可以用钢笔实现
![image](https://user-images.githubusercontent.com/48878568/225630732-fee5d974-8afa-47bf-909b-eaf17e29923b.png)

**Comment by Alsmile** [comment]
1. 自定义图形库： https://doc.le5le.com/document/119832713

2. 使用钢笔工具，然后转换为节点（官网操作：选中右键）
