### ISSUE TITLE
 【建议】钢笔绘制的时候，是否考虑添加吸附功能

### ISSUE THREAD

**Issue by wang11111** [le5le-com/meta2d.js#15]
吸附功能就是每个anchor的实际坐标位置都在网格点上，就是在绘制过程中计算鼠标点击过程中最近的网格点；
在绘制水平线垂直线，以及个性化图形的时候有很大帮助，减少偏移，减少多余一丢丢线条的情况

**Comment by SignDawn** [comment]
目前只有图形吸附，频繁的计算是消耗性能的，如果想绘制水平或垂直的线，
可以在 绘制结束后， 移动线的锚点，锚点与锚点直接存在对齐关系，可以形成水平垂直的线

**Comment by Alsmile** [comment]
已支持
