### ISSUE TITLE
内置表单组件 radio 单选框 通过点击触发 checked 改变时，没有触发update 或者 valueUpdate 消息事件。

### ISSUE THREAD

**Issue by amatiass** [le5le-com/meta2d.js#150]
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/48198890/226560007-c3e1ef6e-5a21-42d1-bb46-a42198efe800.png">
官网的示例在点击更改选中值时数据配置的值也没有实时更新。但是类似的 switch 或者 checkbox 组件就可以触发 valueUpdate 事件。

**Comment by ananzhusen** [comment]
我这边操作是可以的，不知道是否是按照你的思路来操作的，可以提供视频

**Comment by ananzhusen** [comment]
官网已处理
