### ISSUE TITLE
在外层预览界面,open一个图纸之后,svg图形显示黑框

### ISSUE THREAD

**Issue by SunHengX** [le5le-com/meta2d.js#153]
![image](https://user-images.githubusercontent.com/63703285/228104273-e4093aba-ecd3-484f-91f6-ee8e7902c87a.png)
![image](https://user-images.githubusercontent.com/63703285/228104425-6b0ea2e7-bbb5-4fd7-a03e-a6d0b0234841.png)
![image](https://user-images.githubusercontent.com/63703285/228104954-0c1e0854-ac67-4717-b979-5dd2c8d5dffe.png)
![image](https://user-images.githubusercontent.com/63703285/228105095-9336dd61-b571-41d7-803e-7cd7f99966e1.png)
在设计的时候是没有问题的,但是在单独页面预览的时候,svg会变成黑框

**Comment by SignDawn** [comment]
看样子不是 svg 吧，这应该是阿里字体没有加载进来。
https://developer.le5le.com/tutorial/icons.html

**Comment by SunHengX** [comment]
> 看样子不是svg吧，这应该是阿里字体没有加载进来。 https://developer.le5le.com/tutorial/icons.html

还有一个问题,就是当我选中很多个画笔.进行移动的时候,会越来越卡,组合成一个图形拖拽的时候并不卡,但是我监听了画笔的移动,
这样做还是有点卡
![image](https://user-images.githubusercontent.com/63703285/228707701-b3bdf365-58e2-441c-b148-5ecde80f5fce.png)

**Comment by SunHengX** [comment]
> 看样子不是svg吧，这应该是阿里字体没有加载进来。 https://developer.le5le.com/tutorial/icons.html

还有一个问题,就是当我选中很多个画笔.进行移动的时候,会越来越卡,组合成一个图形拖拽的时候并不卡,但是我监听了画笔的移动,
这样做还是有点卡
