### ISSUE TITLE
年前贵公司在线绘图工具更新以后，区分了2d和3d，导致在之前老版本绘制电力SCADA接收数据的代码，在新版本都不生效，更换关键函数meta2d之后，收到的都是类似模拟数据，都不正常了，请问除了更换关键函数为meta2d之外，还需要修改修改什么参数或配置呢

### ISSUE THREAD

**Issue by DLpikaqiu** [le5le-com/meta2d.js#156]

**Comment by ananzhusen** [comment]
只是产品改名，并没有做结构上的改动，可以加入我们官方群（官方文档可查），提供图纸json数据，我们技术人员有时间会帮你看一下。

**Comment by Alsmile** [comment]
0.5.x版本 -> 最新版本：  在2d.le5le.com打开图纸，转换为最新格式数据，然后下载json到自己项目
1.x           -> 最新版本:     无需特别操作
