### ISSUE TITLE
组合图元后，移动一下图元，其中一个基础图元不见了

### ISSUE THREAD

**Issue by x8zx** [le5le-com/meta2d.js#157]
为什么我自己绘制了一个图元，然后组合，我在随便移动一下，其中一个图元就没了，取消组合后他又是好的。
调用了官网提供的combine，但只传了pen参数，没有传showChild参数，为什么会出现这种情况，其他的图元组合不会出现这种情况，有的基础图元组合后，移动一下，其他有些图元就不见了

![1](https://user-images.githubusercontent.com/112915069/229047500-dd7bd7b6-283f-4421-801e-a1a908acd2e8.png)
![2](https://user-images.githubusercontent.com/112915069/229047509-a92930d9-8c39-4be0-9421-3a0eb2d57bd2.png)

**Comment by SignDawn** [comment]
官网给个重现链接看看？保存后分享。
或者把 下载 的 json 发出来看看

**Comment by x8zx** [comment]
我自己发现了问题，在自定义图元JS那里写错了一个属性导致了，现在好了
