### ISSUE TITLE
echart图表组合后,组合组件不能移动,组合移动只能依靠未重合部分移动组件

### ISSUE THREAD

**Issue by rolitter** [le5le-com/meta2d.js#158]
在官网 https://2d.le5le.com/

echart图表组合后,组合组件不能移动,组合移动只能依靠未重合部分移动组件
如果图表重合后,就移动不了组合
![meta2d](https://user-images.githubusercontent.com/27326998/230518612-0fe1b6dd-8087-4c6c-8825-699ddba6cd33.gif)

**Comment by SignDawn** [comment]
![image](https://user-images.githubusercontent.com/48878568/230702254-21c658d9-f08c-4c45-843a-1746c95f9ee7.png)

把两个子的 locked 打开就行了
