### ISSUE TITLE
highcharts 相关组件 导出为 png发现导出的组件位置为空白, LightningChart也有相同的问题

### ISSUE THREAD

**Issue by rolitter** [le5le-com/meta2d.js#159]
画布加入highcharts 组件 导出为 png发现导出的highcharts 组件内容为空白
![meta2d2](https://user-images.githubusercontent.com/27326998/230527956-a8f23d5f-2d6f-4fb9-b3d6-da0333219490.gif)

**Comment by ananzhusen** [comment]
一些dom元素图元，不一定能够获取对应图片资源，所以是空白的，不过官网highcharts和lightningchart的已处理

**Comment by rolitter** [comment]
iframe和视频 组件 导出图片还是空白的
