### ISSUE TITLE
canvas is locked, can not drop

### ISSUE THREAD

**Issue by 863446062** [le5le-com/meta2d.js#160]
在画布上快速多次点击，画布就无法拖动了，控制台提示canvas is locked, can not drop
![image](https://user-images.githubusercontent.com/10559788/230540506-5b5db51c-8a8d-4c16-8d2a-e6fee04e7aa7.png)

再点击一次画布  ，才可正常拖动

**Comment by ananzhusen** [comment]
方便测试一下我们官网有没有该问题，有问题的话最好提供操作视频，我们更好定位
