### ISSUE TITLE
【建议】开放Websocket可选参数protocols的设置入口

### ISSUE THREAD

**Issue by ObearO** [le5le-com/meta2d.js#161]
Websocket的构造函数包含一个可选参数 `protocols`，内容是一个协议字符串或者一个包含协议字符串的数组。这些字符串用于指定子协议，这样单个服务器可以实现多个 WebSocket 子协议（例如，您可能希望一台服务器能够根据指定的协议（protocol）处理不同类型的交互）。如果不指定协议字符串，则为空字符串。
```javascript
// used like this
var aWebSocket = new WebSocket(url [, protocols]);
```
目前关于websocket的api中没地方设置，建议可以放开：)

**Comment by Alsmile** [comment]
已添加
