### ISSUE TITLE
成组图元的子图元解锁后删除不掉，并且报错；

### ISSUE THREAD

**Issue by AngelYT** [le5le-com/meta2d.js#162]
topology/core版本时是可以的。官网不报错，并且能删除，但是自己下载meta2d/core后使用会报错；换成和官网一样的版本还是不行。
![image](https://user-images.githubusercontent.com/48871834/231666915-26183ed4-7e17-4184-95c1-4f68094f21c5.png)

**Comment by SignDawn** [comment]
最新的代码应该已经改过了，可能要催一下官方发布新包了，你拉最新的代码，link 一下试试看？
![image](https://user-images.githubusercontent.com/48878568/231970408-aeeb0db3-49e7-450d-bd6a-4bb4c91a5797.png)

**Comment by AngelYT** [comment]
暂时还没解决，应该得等你们更新包了

**Comment by SignDawn** [comment]
去群里催下官方
