### ISSUE TITLE
上一个图层，下一个图层，传入第二个参数无效

### ISSUE THREAD

**Issue by qwe2692693** [le5le-com/meta2d.js#172]
上一个图层，下一个图层，传入第二个参数无效，但是看到数组位置变了，视图没有渲染，只有置顶和置底可以用

**Comment by ananzhusen** [comment]
因为画布中有覆盖关系的两个图元在数组中的位置不一定相邻，所以移动一位（一个图层），并没有改变这两个图元在数组中的先后顺序，‘视觉上’没有变化。而置顶置底是直接将pen放在数组最后/最前

**Comment by qwe2692693** [comment]
根本就没变，置顶置底看代码是把整个pen和他的子级拆开一起放的，上一层下一层是放的整pen而没有把子级也放，怎么试了都没反应

**Comment by ananzhusen** [comment]
上/下一层确实没有考虑组合节点的子节点们，因为组合后，被组合的子节点在pens的位置（索引）不一，上/下一层要怎么移动这些子节点，这没有合适的方法，所以目前不予处理。而且，如果想改变视觉上的上下层级关系，置顶置底是足够了的。

**Comment by SignDawn** [comment]
up 第二个参数怎么传的？这个方法实在是不太推荐使用。
可以试试 upByArea ，详细可以看看这个问题 https://github.com/le5le-com/meta2d.js/issues/151

**Comment by Alsmile** [comment]
第二个参数已废弃
