### ISSUE TITLE
image gif 类型切换bug

### ISSUE THREAD

**Issue by Blizzard-liu** [le5le-com/meta2d.js#175]
![666](https://github.com/le5le-com/meta2d.js/assets/20244432/f90b52cf-61e4-4b0d-b65a-49d615a9da25)
[test (2).zip](https://github.com/le5le-com/meta2d.js/files/11503121/test.2.zip)
![bf07ec547abfd836ea06722fe306170](https://github.com/le5le-com/meta2d.js/assets/20244432/bbe5e14e-a203-46ea-b928-fda8e2e9f529)

**Comment by ananzhusen** [comment]
这是在你代码基础上改的示例代码
![image](https://github.com/le5le-com/meta2d.js/assets/48847159/cc023c8d-3c4c-420a-a17a-614844f1abd5)

**Comment by Blizzard-liu** [comment]
还是没看懂我的逻辑错哪了  按照你这个写法 多个图片判断怎么写呢

**Comment by ananzhusen** [comment]
你不能在遍历的时候去改数据，又用这个数据去做判断处理

**Comment by Blizzard-liu** [comment]
![image](https://github.com/le5le-com/meta2d.js/assets/20244432/036ff571-60a7-4907-ad00-a90e7d91d1a2)

确实不太对  tag应该改成id

时间改小一点 问题还是一样的  gif图片没有remove

**Comment by Blizzard-liu** [comment]
@ananzhusen 
![image](https://github.com/le5le-com/meta2d.js/assets/20244432/39ed4533-e055-4806-83e4-c361fe4b2ee1)
你这个写法 时间改小点  就可以复现了

**Comment by Alsmile** [comment]
#166  可能是同一个问题，这里先关联

**Comment by SignDawn** [comment]
看了下源码，当按如下流程执行时
1. 切换成 gif 图片，开始加载 gif 图片，目前加载未完成，未插入 dom 树
2. gif 未加载完成，切换成 image 图片，会去销毁 dom 树中的 gif ，但 gif 还未加载完成，未插入 dom 树，所以没有销毁
3. gif 终于加载完成，插入到 dom 树，该 gif 成为一个没有引用（指针）指向到它的 dom ，且后续都不会被销毁了
按照这个流程执行，就会出现问题，所以 定时器 时间越短，越容易出现问题。

**Comment by SignDawn** [comment]
https://github.com/le5le-com/meta2d.js/pull/184

**Comment by SignDawn** [comment]
可查看这个 pr ，可以解决这个问题，思路在于
gif onload 回调执行时，若当前 pen 对应的 gif 与本次回调加载的 img 不是同一个，那么就不插入到 dom 中

**Comment by Blizzard-liu** [comment]
666  大佬就是牛逼
