### ISSUE TITLE
从桌面拖拽一个图片到画布中，下载 png 报错

### ISSUE THREAD

**Issue by SignDawn** [le5le-com/meta2d.js#176]
预测是官方使用了新的图片上传地址，导致图片在 canvas 上跨域。
在 fileToPen 方法中 new Image() 添加   img.crossOrigin = 'anonymous'; 即可。
望测试一下，本地没有图片上传的环境，不便测试。
![image](https://github.com/le5le-com/meta2d.js/assets/48878568/dce1d939-ab1a-4f71-aae8-99627620082f)

**Comment by ananzhusen** [comment]
已完善
