### ISSUE TITLE
请问pen的zIndex不起作用是怎么回事，应该怎么设置层级使得获取数据后能够显示传到后台的层级关系

### ISSUE THREAD

**Issue by lzhleon** [le5le-com/meta2d.js#178]

**Comment by SignDawn** [comment]
大部分画笔都不是 dom 类型的，zIndex 是不生效的。
它的层叠关系仅仅取决于 data.pens 的数组顺序，index 越大越上层。
考虑使用 up, down ，top, bottom ，upByArea 等 api 来更改画笔的层级顺序

**Comment by Alsmile** [comment]
原生图元用  up, down ，top, bottom 等修改顺序；通过 data.pens 的数组顺序获取层级

外部dom图元，通过zIndex修改顺序

**Comment by lzhleon** [comment]
感谢您的解答



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Alsmile ***@***.***&gt;
发送时间: 2023年6月2日 08:53
收件人: le5le-com/meta2d.js ***@***.***&gt;
抄送: lzhleon ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [le5le-com/meta2d.js] 请问pen的zIndex不起作用是怎么回事，应该怎么设置层级使得获取数据后能够显示传到后台的层级关系 (Issue #178)





 
Closed #178 as completed.
