### ISSUE TITLE
监听系统消息中click事件时，获取画布节点信息错误

### ISSUE THREAD

**Issue by 2276692243** [le5le-com/meta2d.js#179]
具体操作如下：鼠标点击触发前端弹框，弹框遮罩层隔开鼠标与画布，然后鼠标移动到其他节点点击触发取消遮罩层，此时鼠标位置已经移动到其他节点，但是这时点击节点，系统消息click事件回调函数携带的参数还是上一个节点的信息
经过测试，在鼠标取消遮罩层后，需要通过移动鼠标才能正确获取节点信息

**Comment by SignDawn** [comment]
可以试试 弹出对话框 以后，手动清除一下 meta2d.store.hover = null;

**Comment by Alsmile** [comment]
弹框后，画布捕捉不到任何事件了，因此无法做鼠标事件处理。暂时只能自己在合适的时候，调用 meta2d.clearHover()告知鼠标已移走。  meta2d.inactive
