### ISSUE TITLE
画布的滚动时间可以监听到没

### ISSUE THREAD

**Issue by qwe2692693** [le5le-com/meta2d.js#181]
画布的滚动时间可以监听到没

**Comment by ananzhusen** [comment]
滚动事件可以自己监听WheelEvent处理，官方用touchStart=performance.now()记录前后两次的时间差。具体可以看核心库实现

**Comment by SignDawn** [comment]
缩放画布 scale 消息是否满足你的要求？
meta2d.on('scale', () => {})

**Comment by Alsmile** [comment]
1. 禁止滚动缩放的情况下：例如，meta2d.setOptions({disableScale:1})
document.addEventListener('wheel', ()=>{...});

2. 默认滚动缩放时：
    meta2d.on('scale', () => {...})

自行在以上函数中监听时间变化
