### ISSUE TITLE
给控件添加自定义事件行为，触发该事件时，core.ts会在控制台打印http消息发送成功，这个是底层内置的吗？

### ISSUE THREAD

**Issue by tan-903835793** [le5le-com/meta2d.js#183]

**Comment by tan-903835793** [comment]
我设置的就是发送绑定数据，我看控制台打印的'http消息发送成功'这个条件满足我接下来的需求，所以想请教一下，如何触发我绑定的对应的事件

**Comment by ananzhusen** [comment]
看你事件类型是啥，如果配有触发条件，要条件成立后才触发事件，还有事件执行需要锁定画布，

**Comment by tan-903835793** [comment]
我现在是发送绑定数据，事件中选择其中一种事件如单击、双击、值变化、移入、移出......，然后触发某个元素绑定的事件如单击，此时执行我需要的逻辑，附上我写的代码：
`onMessag(event, data) {
      // console.log(event)
      switch (event) {
        case 'dblclick':
          this.doDbClick(event, data)
          // console.log('dbclick', data)
          break
        case 'click':
          this.doClick(event, data)
          // console.log('click', data)
          break
        case 'enter':
          this.Enter(event, data)
          break
        case 'leave':
          this.Enter(event, data)
          break
        case 'active':
          this.Enter(event, data)
          break
        case 'inactive':
          this.Enter(event, data)
          break
        case 'mousedown':
          this.doClick(event, data)
          break
        case 'mouseup':
          this.doClick(event, data)
          break
        default:
          break
      }
    },
    doClick(event, data) {
      if (data?.pen?.events?.length) {
        data.pen.events.forEach((item) => {
          if (event == item.name) {
            console.log('hahahahhahahahah')
          }
        })
      }
    },`
`this.meta2d.on('*', this.onMessag)`
不清楚我这个监听逻辑是否正确，而且这个onMessage函数会一直执行，打印socket和valueUpdate，而且我执行鼠标双击的时候，是会先触发单击事件。
**或者直接说，怎么在触发发送绑定数据事件行为的图元的时候拿到对应的执行方法**
感谢！！！

**Comment by SignDawn** [comment]
你监听了全部的事件 * ，onMessage 自然是会多次执行的。你可以直接监听你想要的事件。
https://doc.le5le.com/document/119626293

meta2d.on('click', () => {})

**Comment by SignDawn** [comment]
鼠标双击时，会触发单击事件，原生也是这样的，可以查看下面这个 codesandbox 的例子。
https://codesandbox.io/s/youthful-fire-4xn6zn?file=/src/App.js
![image](https://github.com/le5le-com/meta2d.js/assets/48878568/a661149d-ddc7-466d-ab5a-4aee7305c21d)

**Comment by SignDawn** [comment]
还不太理解你想问什么，如果可以，提供一个 codesandbox

**Comment by tan-903835793** [comment]
大佬，是我没有描述清楚吧，这个问题你那边可以先close掉，感谢！！！
