### ISSUE TITLE
麻烦请问一下重置可视化引擎大小，如何解决画布中图元不会自适应布局的问题

### ISSUE THREAD

**Issue by tan-903835793** [le5le-com/meta2d.js#185]

**Comment by tan-903835793** [comment]
使用meta2d.on('scale', (e) => {e.stopPropagation()})是不生效的，请问源码中有方法阻止缩放吗？

**Comment by tan-903835793** [comment]
使用meta2d.resize(1000, 800);重置可视化引擎大小，画布的大小是被修改了，但是画布中图元是不会自适应布局，请问这个有办法解决吗？

**Comment by ananzhusen** [comment]
fitView centerView等方法，可以看官网文档 https://doc.le5le.com/document/119882449
