### ISSUE TITLE
setValue方法能否更新画笔中某个子对象里的属性值

### ISSUE THREAD

**Issue by xiaohouzi007** [le5le-com/meta2d.js#186]
麻烦问下setValue方法能否更新画笔中某个子对象里的属性值
![image](https://github.com/le5le-com/meta2d.js/assets/32658842/ce0b50a5-a334-46f0-a846-1c5ff55b8ef3)

**Comment by Alsmile** [comment]
子对象也有自己的独立的id，使用子对象的id去修改。获取子对象列表： https://doc.le5le.com/document/119895613#children
