### ISSUE TITLE
globalAlpha不能够设置echarts图表中图元的透明度吗？

### ISSUE THREAD

**Issue by 1779856729** [le5le-com/meta2d.js#187]
![1686904710024](https://github.com/le5le-com/meta2d.js/assets/136795818/9b05d7d0-5dab-4ba6-96b5-fb619e62d5ad)
设置了透明度，但是没有效果

**Comment by ananzhusen** [comment]
官网已处理

**Comment by 1779856729** [comment]
谢谢，npm上的包好像还没有更新

**Comment by ananzhusen** [comment]
@meta2d/core@1.0.18

**Comment by 1779856729** [comment]
好的，非常感谢

**Comment by 1779856729** [comment]
@meta2d/core已更新为@1.0.18，但是globalAlpha还是不能够设置echarts图表中图元的透明度。 在控制台打印查看图元中的globalAlpha属性也设置成功，但是不起作用，查看元素的style样式，opacity并没有添加上。

![微信图片_20230625165237](https://github.com/le5le-com/meta2d.js/assets/136795818/aefc153b-e6c8-4b1b-9ee4-eb40f9d9cf49)
![微信图片_20230625165308](https://github.com/le5le-com/meta2d.js/assets/136795818/0f946cba-b932-4fa0-bcaa-d59e8ab520d0)
