### ISSUE TITLE
自定义图表控件出现的问题

### ISSUE THREAD

**Issue by tan-903835793** [le5le-com/meta2d.js#189]
![微信图片_20230707140828](https://github.com/le5le-com/meta2d.js/assets/57447930/8cb0fb5e-3885-4289-882f-d4c2f56d566c)
![微信图片_20230707140917](https://github.com/le5le-com/meta2d.js/assets/57447930/f1fcb732-d44a-4c51-bfb0-890bb4d848dc)
![微信图片_20230707140922](https://github.com/le5le-com/meta2d.js/assets/57447930/717dff01-8266-45c1-a3fe-d0503fa57308)
![微信图片_20230707140926](https://github.com/le5le-com/meta2d.js/assets/57447930/e77a4fa2-d40b-42ac-97a5-e6487619e671)
如果自己自定义图表图元的话，图元名字自定义为echartsh，就会出现每次拖动图元就会新创建一个div标签，透明度自动添加为globalAlpha: 0.5。
README.md中registerNode、loadJS方法，core核心库中没有。

**Comment by ananzhusen** [comment]
1.自定义图元参考：https://doc.le5le.com/document/119832713 或者参考核心库中开源图形库的注册
2.拖动会创建新的div问题options配置domShapes：  https://doc.le5le.com/document/119882449#Options
