### ISSUE TITLE
[Bug]: pointInRect方法 当点坐标存在于矩形边界上时，会被判定为不在rect内

### ISSUE THREAD

**Issue by lzw-leaf** [le5le-com/meta2d.js#202]
### bug描述

pointInRect 方法 当点坐标存在于矩形边界上时，会被判定为不在rect内，嗯，看了下源码，好像是没有做边界判断

### 期待效果

会被判定为在rect内

### 发生频率

每次

### 核心库版本

1.0.23

### 浏览器版本

Chrome  版本 115.0.5790.171

**Comment by Grnetsky** [comment]
当边界很大时，默认是以边框中心线做判断的，这个方法是根据选中框来定义的，不考虑边界值，有需要可以自己去实现一下，动态计算边框再判断即可

**Comment by lzw-leaf** [comment]
自行封装了一个相关方法增加处理了
