### ISSUE TITLE
[Bug]: connectLine方法报错

### ISSUE THREAD

**Issue by liganghui** [le5le-com/meta2d.js#203]
### bug描述

**遇到的问题 :**
connectLine方法 基础调用报错 

![image](https://github.com/le5le-com/meta2d.js/assets/15844198/7a9a499f-d3e5-469f-9c85-044affed1bea)

**复现的代码**
```JavaScript
  const a=  meta2d.store.pens

    var ids=[]
    for(let key in a){
    let value= a[key]
    if(value){
    ids.push(value.id)
    }
    }
const from = meta2d.findOne(ids[0]);
const to = meta2d.findOne(ids[1]);
meta2d.connectLine(from,to);
```

使用的版本 : 
@meta2d/core V1.0.24

### 期待效果

两个矩形中间 建立关系连线

### 发生频率

每次

### 核心库版本

1.0.24

### 浏览器版本

谷歌浏览器

**Comment by liganghui** [comment]
找到了导致 此报错的函数 , 当我注册生命周期时就会报错 ,  移除就正常了
``` JavaScript
meta2d.beforeAddPens =  () => {
        return true;
    };
```

**Comment by ananzhusen** [comment]
connectLine方法调用前提是被连接的图元存在锚点
