### ISSUE TITLE
[Bug]: onScale和onRessize生命周期触发时，onMove也会触发

### ISSUE THREAD

**Issue by lzw-leaf** [le5le-com/meta2d.js#204]
### bug描述

业务上因为需要分别要对画笔的onScale、onResize、onMove 做处理。 发现除自身事件外基本都会触发onMove事件，看了一下源码，主要原因是calcInView方法中内置了一个onMove的触发方式。 calcInView方法本身又有很多函数调用 ，我还注意到有些调用calcInView方法的地方也会再次调用onMove方法，可能会有重复的情况==

### 期待效果

各个生命周期事件之前触发相对独立。不会互相触发。

### 发生频率

每次

### 核心库版本

1.0.23

### 浏览器版本

Chrome  版本 115.0.5790.171

### 其他需要补充的

本来业务层上做个事件间的拦截， 即在每个事件触发时，做记录，如果有进行中事件，则阻止其他事件的触发，但Resize的对应源码里会先触发onMove导致 onResize触发不了。。

**Comment by ananzhusen** [comment]
calcInView方法中为了更新dom图元状态，直接用了onMove周期，没有考虑实际。该问题将在1.0.54版本修复。
