### ISSUE TITLE
如何直接添加一个组合为状态的图元？

### ISSUE THREAD

**Issue by chengandpeng** [le5le-com/meta2d.js#206]
### 建议

现在组合为状态需要添加两个图，调整位置后进行组合。
对用户有一定操作学习成本，是否有办法或适合的API实现直接添加一个组合后的图元？

### 建议原因

降低用户操作成本

**Comment by SignDawn** [comment]
1. 官网，我的组件，创建一个组件
![image](https://github.com/le5le-com/meta2d.js/assets/48878568/dac47bf9-4fee-43f2-8064-dae5610745e5)

2. 拖拽图元的相对位置，设置默认展示第0个或其它，然后保存
![image](https://github.com/le5le-com/meta2d.js/assets/48878568/c419fd2b-50ab-44b9-9d4f-8d8a9c73494b)

3. 在我的组件里就可以找到了，然后拖拽到画布中
![image](https://github.com/le5le-com/meta2d.js/assets/48878568/d04fd2c7-a70e-42c8-b509-3323bec99d72)

**Comment by SignDawn** [comment]
api 使用 toComponent 
https://doc.le5le.com/document/119882449#toComponent

**Comment by chengandpeng** [comment]
> api 使用 toComponent https://doc.le5le.com/document/119882449#toComponent

感谢回复！
您说的官网的方法我试了下，在【我的组件】中点击【创建组件】后报错了，不知道是不是我一个人的问题。
![image](https://github.com/le5le-com/meta2d.js/assets/668072/b878990b-23a2-4a87-81c1-43086a80b74b)

关于 API的 toComponent 方法，
如果我对两个已经添加到画布中的图元执行toComponent方法的话，没什么问题，能生成一个图组。

但是我在拖拽(dragstart)的时候使用的话
```javascript
const component = meta2d.toComponent([{
    "text": "五边形",
    "width": 100,
    "height": 100,
    "name": "pentagon"
  },
  {
    "text": "圆",
    "width": 100,
    "height": 100,
    "name": "circle",
    "type": 0
  }], 0);
```
会报错，可能因为不是完整Pen的实例？
![image](https://github.com/le5le-com/meta2d.js/assets/668072/4f131bbb-d60c-4512-b3a9-6e23beed9ec4)
 ` meta2d/core版本1.0.28`


现在就是希望在没有Pen实例的情况下，直接拖拽出一个combine图组。
请帮忙看下如何实现

**Comment by SignDawn** [comment]
![动画](https://github.com/le5le-com/meta2d.js/assets/48878568/c06d9c97-ea92-4876-9571-430b20f65a59)

gif 里的 组合为状态 没点，是一个误操作。

**Comment by SignDawn** [comment]
你这样对 api 的调用，如何体现两个图元的相对位置关系呢？
我的建议就是这部分的操作交给用户在界面上处理，你只需要存储 toComponent 的结果就好了；可以做一个类似于 官网 一个操作，让用户自己来设置 组合 的位置关系

**Comment by chengandpeng** [comment]
> 你这样对 api 的调用，如何体现两个图元的相对位置关系呢？ 我的建议就是这部分的操作交给用户在界面上处理，你只需要存储 toComponent 的结果就好了；可以做一个类似于 官网 一个操作，让用户自己来设置 组合 的位置关系

因为主要是作为开关图组，所以两个图元的x,y都会默认为0。

正是因为用户对于状态图组的学习成本和操作成本比较高，才想着直接拖出一个组合好的图组用起来更方便。

`meta2d.canvas.addCaches`的方法看起来可以，不过和目前拖拽的方式不一致，用户体验就比较奇怪了。。。

我想的是如果能暴露一个添加pens成功后的回调（现在只有beforeAddPens)，然后addPen/addPens的方法能返回加入好的Pen实例。这样就可以在回调中使用`toComponent`了

**Comment by SignDawn** [comment]
一样的，你按照我的方式，放到 event.dataTransfer.setData 就成

**Comment by chengandpeng** [comment]
> 一样的，你按照我的方式，放到 event.dataTransfer.setData 就成， 重点是数据可以参考上面这个内容。

这样可以实现，谢谢了
