### ISSUE TITLE
[Bug]: 图元线条宽度非常大时，图元变形

### ISSUE THREAD

**Issue by fengbozhi** [le5le-com/meta2d.js#207]
### bug描述

圆形图元，直径为100，设置线条宽度为70时，图元形状发生变形
![image](https://github.com/le5le-com/meta2d.js/assets/19235574/1efdd2d0-3de9-4dc7-9002-c2fcf628063d)

### 期待效果

图元不变性，正常显示

### 发生频率

每次

### 核心库版本

1.0.24

### 浏览器版本

 115.0.5790.111

**Comment by SignDawn** [comment]
把末端样式配置成默认就可以了
![image](https://github.com/le5le-com/meta2d.js/assets/48878568/ee05f512-7227-43a4-853c-e85b6abb8c1d)
![image](https://github.com/le5le-com/meta2d.js/assets/48878568/bf2db3b3-993c-4bda-8c85-55871ec876ef)

**Comment by SignDawn** [comment]
不确定为什么现在 lineCap (末端样式) 的默认值 不是 butt (默认) 了，而是 square (方形) 了。

**Comment by fengbozhi** [comment]
![image](https://github.com/le5le-com/meta2d.js/assets/19235574/2e32d48b-6ed1-4701-8014-0fbe3f465baa)
选择默认，如果选择正方形，也会出问题

**Comment by fengbozhi** [comment]
> 不确定为什么现在 lineCap (末端样式) 的默认值 不是 butt (默认) 了，而是 square (方形) 了。

**Comment by SignDawn** [comment]
可能是这个原因，导致 官方的默认 成了 square 方形。

你可以暂时对圆做一下特殊处理，将圆的 lineCap 更改成默认。（正方形不更改）
后续应该会在图形绘制上来解决这个问题。
