### ISSUE TITLE
[Bug]: 图元无内容时，输入光标，垂直居中不生效

### ISSUE THREAD

**Issue by fengbozhi** [le5le-com/meta2d.js#208]
### bug描述

步骤：
添加矩形
文字设置垂直、水平居中
删除矩形中文本
![image](https://github.com/le5le-com/meta2d.js/assets/19235574/e03f4b0b-d308-49c3-87b7-ad5dc08a219b)

### 期待效果

光标垂直、水平居中

### 发生频率

每次

### 核心库版本

1.0.24

### 浏览器版本

 115.0.5790.111

**Comment by ananzhusen** [comment]
官网已修复
