### ISSUE TITLE
[Bug]: redo还原无法一步一步还原

### ISSUE THREAD

**Issue by fengbozhi** [le5le-com/meta2d.js#209]
### bug描述

重现步骤：
添加矩形
矩形添加填充色、矩形中输入文字、文字字体加粗
点击【撤销】按钮
点击【还原】按钮

预期结果&实际结果：
预期：
1-2：撤销按照操作步骤一步一步撤销，先撤销字体加粗、再撤销盒子中输入文字
3：还原按照撤销步骤一步步还原到盒子填充颜色、添加文字、文字加粗的效果

实际：
1-2：点击【撤销】后，盒子直接回到添加填充色的状态
3.点击【还原后】，盒子回到添加文字的状态，若步骤1中添加文字和文字加粗的过程中没点击画布，则还原后文字为粗体，若步骤1中添加文字后点击画布，再点击盒子加粗字体，则回退文字为不加粗的字体

### 期待效果

1-2：撤销按照操作步骤一步一步撤销，先撤销字体加粗、再撤销盒子中输入文字
3：还原按照撤销步骤一步步还原到盒子填充颜色、添加文字、文字加粗的效果

### 发生频率

每次

### 核心库版本

1.0.24

### 浏览器版本

 115.0.5790.111

**Comment by ananzhusen** [comment]
官网已修复
