### ISSUE TITLE
[Bug]: 删除元素后，再撤销，图层顺序跟之前不一致。

### ISSUE THREAD

**Issue by dalaogan** [le5le-com/meta2d.js#210]
### Code Sanbox异常重现

https://2d.le5le.com/

### bug描述

创建1/2/3/4 四个元素
删除掉2
撤销
图层顺序变成了 4231.
再官网就能复现。https://2d.le5le.com/
![1695020035690_9B2552D9-D169-4f41-B19B-0234F22A3F84](https://github.com/le5le-com/meta2d.js/assets/21209179/f631286a-fea3-42e3-85b0-9beb3427fb3b)

### 期待效果

撤销后跟之前的图层顺序一致

### 发生频率

每次

**Comment by ananzhusen** [comment]
官网已改成总是追加到最后
