### ISSUE TITLE
获取画笔层级有api吗 貌似没找到

### ISSUE THREAD

**Issue by FanFanJUN** [le5le-com/meta2d.js#211]
![image](https://github.com/le5le-com/meta2d.js/assets/37857876/ded2b2f6-7ea6-4e74-97a9-b5415307328c)

**Comment by xlcodes** [comment]
<img width="1406" alt="image" src="https://github.com/le5le-com/meta2d.js/assets/90412675/0eb94ff2-2cdf-40c2-8e18-159cc40de4b2">
文档描述的画笔层级是基于zIndex实现，跟CSS中的z-index一样，你可以试试看。

**Comment by xlcodes** [comment]
通过看源码，针对画笔层级的处理貌似是通过window.meta2d.store.data.pens，处理画笔数组的排列顺序实现的。可能作者有自己的考虑。如果确实需要获取画笔层级的话，可以通过window.meta2d.data()?.pens，获取当前画笔在数组中的位置拿到，修改层级的话不知道能不能实现。官网文档提供的就置顶、置地、置为上一层和置为下一层这4种方式调整层级。

**Comment by SignDawn** [comment]
按截图来看，这里的中层指的是在真实画布 dom 的哪一层。
为了性能优化，目前是有多个真实的 canvas dom 元素的。
非 dom 图元中，图片分布在 上层或下层，其他图元就是在中层，更改图片图元的 isBottom 属性（setValue），可以使图片图元改变层级。
![image](https://github.com/le5le-com/meta2d.js/assets/48878568/7d552c88-ede0-4ed5-b135-8ccff0859258)
一个图片盖住矩形，另外一个被矩形盖住。
![image](https://github.com/le5le-com/meta2d.js/assets/48878568/9245c897-effe-4e2d-b166-3d8946443a6e)
![image](https://github.com/le5le-com/meta2d.js/assets/48878568/8948e460-cc8e-4643-9e83-7963bd9f1b61)

**Comment by SignDawn** [comment]
https://doc.le5le.com/document/119294704#10.%E5%9B%BE%E7%89%87%E8%A6%86%E7%9B%96%E6%96%87%E5%AD%97%E6%88%96%E8%80%85%E5%9B%BE%E5%85%83%E9%97%AE%E9%A2%98
