### ISSUE TITLE
[Bug]: 完全水平的连线，双击无法触发输入事件

### ISSUE THREAD

**Issue by fengbozhi** [le5le-com/meta2d.js#212]
### bug描述

1.拖拽两个一样大小矩形图元，放置水平位置
2.中间连接一条，水平连线
3.鼠标移入连线，双击

![image](https://github.com/le5le-com/meta2d.js/assets/19235574/084327b4-ec97-4f25-96e6-59a755cf1259)

预期结果：

实际结果：
未触发连线，文本输入

### 期待效果

触发连线，文本输入

### 发生频率

每次

### 核心库版本

官网绘制

### 浏览器版本

 115.0.5790.111

**Comment by ananzhusen** [comment]
官网已修复
