### ISSUE TITLE
[Enhancement]: 支持自定义刻度尺

### ISSUE THREAD

**Issue by chenchenpp** [le5le-com/meta2d.js#215]
### 建议

希望能够支持自定义刻度尺的单位，长度和刻度数

### 建议原因

发现目前刻度尺默认的宽度和刻度都是固定的，貌似没发个性化处理。所以在一些单位，比例要求场景中，刻度尺无法发挥作用

**Comment by ananzhusen** [comment]
官方刻度值和图元坐标是对应的。个性化处理是希望支持哪些可配置项，请结合具体的场景说明。

**Comment by 2276692243** [comment]
希望能支持标尺自定义水平和纵向的x轴y轴自定义，就是某些行业比如agv小车配置时，水平为y轴，纵向为x轴，且正负方向更传统坐标系刚好相反，希望能自定义标尺正负方向。另外就是希望能在标尺左上角能自定义比例尺和比例尺说明。在agv地图编辑时通常需要显示比例尺，来表示画布上的单位和实际单位的比例。
