### ISSUE TITLE
[Enhancement]: 建议给WebSocket添加异常捕获机制或重连次数限制

### ISSUE THREAD

**Issue by xlcodes** [le5le-com/meta2d.js#217]
### 建议

目前存在问题：目前Meta2d.js连接websocket暂无连接错误捕获机制，如果用户在图纸传递了异常的ws地址，会导致ws一直重新连接，并且会输出console.info日志。频繁的console有可能会导致内存泄露。
<img width="1552" alt="image" src="https://github.com/le5le-com/meta2d.js/assets/90412675/730e5b0c-f680-4afd-8209-a63ff767777f">

建议增加连接异常捕获机制，向外抛出l连接异常消息；或者内置重连次数，由用户控制在重新连接N次后关闭连接。

### 建议原因

如上处理可以提升用户体验，且减少由于频繁输出日志导致内存泄露。

**Comment by ananzhusen** [comment]
将在@meta2d/core 1.0.54 版本新增 option->reconnetTimes 配置
