### ISSUE TITLE
[Enhancement]:  背景图是否可以跟随画布缩小放大而放大，或者图形背景图跟随

### ISSUE THREAD

**Issue by hsbtr** [le5le-com/meta2d.js#219]
### 建议

是否API或者Options属性可以设置背景图跟随缩小放大

### 建议原因

有一个应用场景希望背景图可以跟随放大缩小

**Comment by SignDawn** [comment]
建议用 一个大的图片节点 放在下层，这样就可以跟随缩小放大了。
https://2d.le5le.com/?id=6128887203582f00012b8a14

可以参照这个 例子

**Comment by ananzhusen** [comment]
可以设置画布尺寸（options设置width&height），参考效果乐吾乐大屏可视化  https://v.le5le.com/
