### ISSUE TITLE
[Bug]: changePenId方法不会同时更新关联数据吗？

### ISSUE THREAD

**Issue by qdonglu** [le5le-com/meta2d.js#220]
### bug描述

![image](https://github.com/le5le-com/meta2d.js/assets/34566933/ba17795c-0405-49f0-9784-701cd9d9f8c1)
如题。

### 期待效果

改变一个节点的id，使用这个节点的旧id都能同步更新。

### 发生频率

每次

**Comment by ananzhusen** [comment]
官网已处理更新，问题将在@meta2d/core 1.0.53被修复
