### ISSUE TITLE
[Bug]: 官网修改矩形图元中的文本，然后直接下载json时，配置中文本不正确

### ISSUE THREAD

**Issue by fengbozhi** [le5le-com/meta2d.js#221]
### bug描述

1.官网环境中新建画布
2.添加正方形图元
3.双击正方形图元
4.将正方形图元中文本修改为“888”
5.选择“文件 > 下载JSON文件”

### 期待效果

预期效果: 下载的json文件中，图元文本为”888“
实际效果：下载的json文件中，图元文本为”正方形“

### 发生频率

每次

### 核心库版本

最新

### 浏览器版本

最新

**Comment by SignDawn** [comment]
结束编辑态才会生效，可以点空白在下载

**Comment by fengbozhi** [comment]
> 结束编辑态将会生效，可以点空白在下载

还有其他方法吗？比如调用某个方法，实现结束编辑态

**Comment by SignDawn** [comment]
hideInput 试试看？在保存前调用
