### ISSUE TITLE
[Bug]: 带图片的矩形显示后图片被遮挡

### ISSUE THREAD

**Issue by xiaohouzi007** [le5le-com/meta2d.js#223]
### bug描述

在画布上先后添加了一个矩形pen和一个带有图片的矩形pen，第一个矩形pen的background ="rgba(255, 255, 255)",则带有图片的矩形pen显示不出图片；如果第一个矩形pen的background ="rgba(255, 255, 255，0)"，则带有图片的矩形pen能显示出图片。麻烦问下这个是啥原因导致的，没有被盖住，因为带有图片的矩形pen能被选中，只是里面的图片被盖住了
![image](https://github.com/le5le-com/meta2d.js/assets/32658842/2205579a-4f51-4b6e-8fe5-7d8ef1701b9c)

### 期待效果

不要盖住图片

### 发生频率

每次

**Comment by SignDawn** [comment]
多层 canvas 结构带来的，图片在单独的层，切换到中层或上层即可。
![image](https://github.com/le5le-com/meta2d.js/assets/48878568/7e0dd27e-4043-4d80-9be9-291e72f3c70a)
