### ISSUE TITLE
[Enhancement]: 使用echarts时候更新数据会重新渲染图表

### ISSUE THREAD

**Issue by ChaCyj** [le5le-com/meta2d.js#224]
### 建议

每次echarts图表数据更新之后,图表被重新渲染了,本来选中图表的一项在查看数据,这个选中状态会丢失,是否可以解决呢

### 建议原因

图表每次更新数据都重新渲染了

**Comment by ananzhusen** [comment]
官方编辑器已经修复更新，问题将在下个版本 @meta2d/chart-diagram 1.0.8版本被修复
