### ISSUE TITLE
[Bug]: core.ts/js文件编译报错

### ISSUE THREAD

**Issue by yejun365** [le5le-com/meta2d.js#225]
### bug描述

core.ts文件sendDataToNetWork等函数中/(?<=\$\{).*?(?=\})/g 首尾未加引号字符，编译失败，同样的错误在该文件中还有两处

### 期待效果

编译正常

### 发生频率

每次

### 核心库版本

1.0.35

**Comment by Grnetsky** [comment]
请提供相关代码以及图片

**Comment by yejun365** [comment]
回复有点官僚化，代码是你们开发的，我这边没必要提供你们开发的代码吧？ 在问题描述中，已经说清楚在哪个文件哪个函数中

**Comment by yejun365** [comment]
![1111](https://github.com/le5le-com/meta2d.js/assets/47526650/4ccc7404-78a3-423f-96f5-874c58d47589)

**Comment by Grnetsky** [comment]
您误解我的语气了，后面我们会排查此问题，感谢反馈，祝您新年快乐

**Comment by yejun365** [comment]
好的，那应该是我误解了，感谢你们的辛勤付出

**Comment by ananzhusen** [comment]
核心库主要语言是typescript,推荐使用 visial studio/HBuilder/WebStorm等开发工具，编译打包推荐使用yarn/pnpm
