### ISSUE TITLE
[Bug]: combine方法卡死

### ISSUE THREAD

**Issue by sensiki** [le5le-com/meta2d.js#226]
### bug描述

调用this.topology.combine(this.topology.store.data.pens)会卡死

### 期待效果

解决问题

### 发生频率

每次

**Comment by Grnetsky** [comment]
topology已经废弃了，请更新到最新版meta2d

**Comment by sensiki** [comment]
就是meta2d，您可以试试，拖几个组件，执行一下combine，参数使用全部的组件

**Comment by sensiki** [comment]
![image](https://github.com/le5le-com/meta2d.js/assets/4695650/2dca3fd4-161b-4cba-a916-6a4b45a4245d)
