### ISSUE TITLE
这个ｍｅｔａ２ｄ．ｊｓ是数据驱动视图可以和ｖｕｅ．ｊｓ集合使用吗？

### ISSUE THREAD

**Issue by WREQI** [le5le-com/meta2d.js#227]
ｖｕｅ也是数据驱动视图，它们相互之间不会冲突重复而影响性能吗？

**Comment by Grnetsky** [comment]
不会，两个数据驱动的原理不同，vue是数据劫持后进行页面刷新，meta2d依赖canvas，通过requestAnimationFrame在每一个动画循环中进行界面更新，两者互不影响

**Comment by WREQI** [comment]
> 不会，两个数据驱动的原理不同，vue是数据劫持后进行页面刷新，meta2d依赖canvas，通过requestAnimationFrame在每一个动画循环中进行界面更新，两者互不影响

相当于这里的数据驱动视图，指的是更新canvas视图，而不是ui界面是吗？

**Comment by Grnetsky** [comment]
> > 不会，两个数据驱动的原理不同，vue是数据劫持后进行页面刷新，meta2d依赖canvas，通过requestAnimationFrame在每一个动画循环中进行界面更新，两者互不影响
> 
> 相当于这里的数据驱动视图，指的是更新canvas视图，而不是ui界面是吗？

对的，meta2d的数据驱动只与canvas有关，并不会在vue上视图更新。
