### ISSUE TITLE
[Enhancement]:  echarts 升级 5.x 大版本

### ISSUE THREAD

**Issue by huxingye** [le5le-com/meta2d.js#228]
### 建议

目前乐吾乐 chart-diagram  引用的 echarts 是 4.9  ，有点旧了。
希望官方升级 echarts 5.4.x 

### 建议原因

我们项目 使用的 阿里云 antd ， echarts  用的5.4
引入 chart-diagram 会导致包不兼容。无法使用。

**Comment by huxingye** [comment]
建议不要再依赖 @type/echarts 了，更新又慢。
直接使用   echarts 5.x 的版本重构了  echarts 5  也还是用TS写的了

**Comment by ananzhusen** [comment]
新版本应该是从全局拿到echarts，用户可以按需下载echarts官方源码包，保证在注册echarts图元前引入echarts源码版即可。官方目前使用版本是5.3.x
