### ISSUE TITLE
[Bug]: mac OS系统两根手指轻触“触摸板”，无法触发“contextmenu”事件

### ISSUE THREAD

**Issue by fengbozhi** [le5le-com/meta2d.js#229]
### bug描述

官网编辑图时，mac OS系统两根手指轻触“触摸板”，无法触发“contextmenu”事件，弹出右键菜单

### 期待效果

mac OS系统两根手指轻触“触摸板”，弹出右键功能菜单

### 发生频率

每次

**Comment by SignDawn** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/API/Element/contextmenu_event

双指按下就有了。
contextmenu mdn 的 demo 也是的，触摸无，双指按下有

**Comment by SignDawn** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/API/MouseEvent/button

代码基于 mousedown button = 2 实现

**Comment by fengbozhi** [comment]
是的，只是轻触不行

**Comment by ananzhusen** [comment]
<img width="662" alt="a79447d405169fee7bce638c16e4e55" src="https://github.com/user-attachments/assets/b8e979f0-4e6e-4fef-a32b-f271fee19cec">
你需要在系统偏好设置-触控板-中设置“轻点来点按”
