### ISSUE TITLE
[Bug]: svg图标创建的图元 没有锚点

### ISSUE THREAD

**Issue by yynyynyyn** [le5le-com/meta2d.js#232]
### bug描述

svg图标创建的图元 没有锚点可以连线

### 期待效果

希望可以出现锚点连线

### 发生频率

每次

**Comment by SignDawn** [comment]
可以用快捷键 a 来添加锚点。

svg 没有锚点可以连线，有 demo 吗？

**Comment by Alsmile** [comment]
有线条的两端的会自动添加锚点，其他场景，需要选择图元，用快捷键A添加自定义锚点
