### ISSUE TITLE
拖拽添加图元到画布可以直接传 pen 对象吗，转成 json 字符串会导致 pen中定义的方法丢失

### ISSUE THREAD

**Issue by Justicx26** [le5le-com/meta2d.js#233]

**Comment by SignDawn** [comment]
基于 ondrop 来实现，event.dataTransfer.getData 只能拿到字符串。
解决方法：
考虑使用 addCaches 来实现，不基于 ondragstart .

其它解决方案应该也有，麻烦提供一个 codesandbox 的 demo

**Comment by ananzhusen** [comment]
也可以监听add消息，给图元添加方法 https://doc.le5le.com/document/119626293
