### ISSUE TITLE
[Bug]: 安卓端点击图元会触发单击事件两次

### ISSUE THREAD

**Issue by ChaCyj** [le5le-com/meta2d.js#235]
### Code Sanbox异常重现

No response

### bug描述

安卓端点击带单击事件的图元会触发单击事件两次

### 期待效果

请求解决办法

### 发生频率

每次

### 核心库版本

1.0.35

### 浏览器版本

chrome

### 其他需要补充的

请求解决办法

**Comment by ananzhusen** [comment]
移动端需要通过webview方式嵌入，官方小程序（乐吾乐）测试没问题，测试示例： https://2d.le5le.com/?id=01910320-c16f-7d84-b423-cd09f1044fec&r=1722334363906&component=false
