### ISSUE TITLE
[Bug]: 组合图元给子图元添加动画，然后多缩放画布几次会出现显示异常

### ISSUE THREAD

**Issue by cosmoscatts** [le5le-com/meta2d.js#236]
### bug描述

**复现步骤：**
- 在 [https://2d.le5le.com/](https://2d.le5le.com/) 中添加个两个基本图元
- 给其中一个添加动画如上下跳动
- 组合两个图元
- 多次缩放画布
- 图元会出现变形错位

### 期待效果

正常缩放，动画不影响缩放

### 发生频率

每次

**Comment by Grnetsky** [comment]
在生产环境中，几乎没有需要频繁去缩放画布的需求，在开发环境中，你需要将页面布局好了后再去执行动画和组合

**Comment by cosmoscatts** [comment]
这是个预览显示界面，有告警会有动画，这时候如果缩放会出现错位，也不需要频繁的缩放，正常的缩放也会出现错位（图元在播放动画时进行缩放）。

有什么好的解决办法吗？禁止缩放好像也不太合理，内容过多时需要缩放，但是会出现错位的问题。

**Comment by cosmoscatts** [comment]
不知道有没有提供类似 beforeAddPens 这样的钩子，beforeScale afterScale，在缩放时手动停止动画？

**Comment by Grnetsky** [comment]
> beforeAddPens

https://doc.le5le.com/document/119668812 看这个文档，寻找合适的钩子进行尝试

**Comment by cosmoscatts** [comment]
onXXX 以 `on` 开头的好像都是已经执行后的回调，好像并不能在执行前拦截

**Comment by ananzhusen** [comment]
官网已处理更新，问题将在@meta2d/core 1.0.53被修复
