### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Ethan-Jan** [le5le-com/meta2d.js#238]
### bug描述

2d可视化图纸切换标签页，再切回，图纸背景色变回成了白色

### 期待效果

2d可视化图纸切换标签页，再切回，图纸背景色还是原本图纸设置的背景色

### 发生频率

每次

**Comment by Grnetsky** [comment]
Chromium内核的bug，参阅https://issues.chromium.org/issues/328755781，等chromium更新或者使用火狐吧

**Comment by Grnetsky** [comment]
Chromium内核的bug，参阅https://issues.chromium.org/issues/328755781，等chromium更新或者使用火狐吧

**Comment by Grnetsky** [comment]
Chromium内核的bug
参阅https://issues.chromium.org/issues/328755781    
等chromium更新或者使用火狐吧]
