### ISSUE TITLE
[Bug]: 1.0.43版本 右键复制功能会复制出来三个

### ISSUE THREAD

**Issue by mythlight123** [le5le-com/meta2d.js#243]
### bug描述

 1.0.43版本 右键复制功能会复制出来三个，会有一个卡在画布上
![fuzhibug](https://github.com/le5le-com/meta2d.js/assets/96294069/c3bb5d4c-eba3-434a-98dd-96639b4dfde6)

### 期待效果

复制功能正常

### 发生频率

每次

### 核心库版本

v1.0.43

**Comment by mythlight123** [comment]
[fuzhibug](https://github.com/le5le-com/meta2d.js/assets/96294069/b6019b13-1d13-4315-a5e4-844c124c0fad)

**Comment by ananzhusen** [comment]
官方2d可视化/大屏可视化未复现此问题，可以尝试升级到最新版本
