### ISSUE TITLE
[Enhancement]: setValue 当 path 中为数字时，创建 [] 而不是 {}

### ISSUE THREAD

**Issue by fdxxw** [le5le-com/meta2d.js#245]
### 建议

1. setValue 的 path 中为数字时，创建 [] 而不是 {}
2. 例如 path = a.b.0，希望创建 {a: {b: [v]}}，而不是 {a: {b: {0: v }}}

![Snipaste_2024-07-23_10-49-25](https://github.com/user-attachments/assets/a4bb8329-c2bf-47b6-a65e-1f5948d69896)

### 建议原因

1. 属性为数组时，需要先内置为空数组 []

**Comment by Grnetsky** [comment]
感谢反馈，在js中数组本质是属性名为数字（会隐式转换为字符串）的对象，由于此处并不依赖于数组的私有方法，为了数据的一致性，避免冗余代码，认为此处无需修改
