### ISSUE TITLE
[Bug]: ctrl c+v 复制会复制三个

### ISSUE THREAD

**Issue by mythlight123** [le5le-com/meta2d.js#247]
### bug描述

ctrl c+v 复制会复制三个
![image](https://github.com/user-attachments/assets/fa4313ff-4c9b-4cb7-87f7-c920d2609e4a)

### 期待效果

默认cv复制出两个

### 发生频率

每次

### 核心库版本

v1.0.51

### 浏览器版本

谷歌

**Comment by ananzhusen** [comment]
官方2d/大屏编辑器没测试出来，看看是不是误操作。

**Comment by mythlight123** [comment]
没有误操作，确实只按了一次ctrl+c ctrl+v，复制出来三个后，有一个被定住了不能删除，使用快捷键会出问题，右键调用api不会出错

**Comment by mythlight123** [comment]
是ctrl +v 的问题，ctrl+c 然后右键粘贴也不会出现三个

**Comment by ananzhusen** [comment]
可能是图元问题，请分享一下图纸id
![image](https://github.com/user-attachments/assets/643a52ae-ccfd-4433-a834-c530a30243b1)

**Comment by mythlight123** [comment]
是在本地用的，把方法换成api调用了
