### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by liuzeWeb** [le5le-com/meta2d.js#248]
### bug描述

使用 connectLine 会触发 addpen 事件。 当触发addpen 事件时候想把连接线变成曲线。
或者有没有其他自动创建连接线，生成曲线的方法

### 期待效果

自动连线生成曲线

### 发生频率

每次

### 核心库版本

1.0.51

### 浏览器版本

chorem 126.0.6478.128

**Comment by ananzhusen** [comment]
connectLine 会生成一条连线所以会触发addPen,你可以监听“add”消息(https://doc.le5le.com/document/119626293)，调用updateLineType 去更新line类型
