### ISSUE TITLE
[Bug]: 执行destroy销毁实例后，GPU占用没有降低

### ISSUE THREAD

**Issue by chen-junqiao** [le5le-com/meta2d.js#249]
### Code Sanbox异常重现
https://codesandbox.io/p/devbox/hungry-hill-4584z5
_No response_

### bug描述

步骤1：new Meta2d(xx, xx)，使用open方法打开图纸
步骤2：执行destroy销毁实例
重复多次步骤1，2，使用浏览器任务管理器查看GPU占用，会累加一直没有降低
我的页面初始GPU占用为：5168k，执行10次后GPU占用为143716k，继续执行会继续累加，导致机器卡死
图纸数据有文字，连线和图片

### 期待效果

执行destroy销毁实例后，GPU占用降低

### 发生频率

每次

### 核心库版本

1.0.48

### 浏览器版本

Microsoft Edge 版本 127.0.2651.86 (正式版本) (64 位)

**Comment by ananzhusen** [comment]
试试每次打开图纸数据的时候 ，深拷贝一下， 例如 meta2d.open(JSON.parse(JSON.stringify(data)))

**Comment by chen-junqiao** [comment]
> 试试每次打开图纸数据的时候 ，深拷贝一下， 例如 meta2d.open(JSON.parse(JSON.stringify(data)))

不行，GPU占用还是一样高

**Comment by ananzhusen** [comment]
![image](https://github.com/user-attachments/assets/bccff66e-ee91-4e66-9f4b-5fda4078a58b)
先在销毁前 添加这段代码 meta2d.canvas.parentElement.innerHTML = ''; 用于释放dom元素。这是因为一个vue页面只会创建一个meta2d对象，而vue等框架会自动销毁dom，没有考虑在一个页面频繁创建meta2d对象这种的情况，下个版本我们会处理这个问题。

**Comment by chen-junqiao** [comment]
> ![image](https://private-user-images.githubusercontent.com/48847159/368479389-bccff66e-ee91-4e66-9f4b-5fda4078a58b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDc4NzcsIm5iZiI6MTcyNjY0NzU3NywicGF0aCI6Ii80ODg0NzE1OS8zNjg0NzkzODktYmNjZmY2NmUtZWU5MS00ZTY2LTlmNGItNWZkYTQwNzhhNThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA4MTkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMGVmZjk1NjZiMWIzZjdlYTQyYTk1N2M2MTAyOTIyZDQyYTJmZTgyMGY4NjZhZGM5OGM1MmMzOWEyNWI3MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DaT2uLBvZ-in7tnYGOSVwS3l3B0IhrlPlTU-t48ipBI) 先在销毁前 添加这段代码 meta2d.canvas.parentElement.innerHTML = ''; 用于释放dom元素。这是因为一个vue页面只会创建一个meta2d对象，而vue等框架会自动销毁dom，没有考虑在一个页面频繁创建meta2d对象这种的情况，下个版本我们会处理这个问题。

确实可以
