### ISSUE TITLE
[Bug]: 多个图或文字【组合】或【组合为状态】后无法保存方案

### ISSUE THREAD

**Issue by Ceeson** [le5le-com/meta2d.js#253]
### bug描述

我是用的“大屏可视化设计器”，前两天用还没啥问题，昨天开始出现这个问题了。

**问题**：选中多个图表或者图+文字任意右键选择【组合】或【组合为状态】，点击“保存为方案”时控制台出现报错
![image](https://github.com/user-attachments/assets/0073e84c-4586-486a-908f-44233256ca7e)

### 期待效果

【组合】或【组合为状态】后能正常保存

### 发生频率

每次

**Comment by ananzhusen** [comment]
官网已修复
