### ISSUE TITLE
[Bug]: 放大镜为何不能放大诸如echats类的图表

### ISSUE THREAD

**Issue by huanyou3** [le5le-com/meta2d.js#255]
### bug描述

 放大镜不能放大诸如echats类的图表

### 期待效果

可以放大图表

### 发生频率

每次

**Comment by Grnetsky** [comment]
echarts属于dom，目前放大镜只针对canvas层进行了处理，dom这一层放大的功能不方便实现

**Comment by ananzhusen** [comment]
最新的版本中，支持echarts生成对应的图片进行放大，但是无法保证是最新的数据内容。
