### ISSUE TITLE
[Enhancement]: 锚点常显

### ISSUE THREAD

**Issue by Terrency** [le5le-com/meta2d.js#256]
### 建议

首先十分感谢做出如此精彩的产品
我们需要一个锚点常显的功能（而不是随着鼠标经过才会显示），查阅了文档，发现没有相关内容，可否帮助提供一个临时解决方案和产品增强设计计划

### 建议原因

部分SysML设计中会将组件接口定义为组件的一部分，接口本身具备一定的业务含义，需要组件接口和组件本身整体显示，而不是鼠标经过才显示，这种设计是不是与现有的设计有差异，又或者是我需要单独设计一个接口展示层，与锚点控制层对应起来

**Comment by Terrency** [comment]
不知道咱们是否有这样的设计
展示层：不可变换元素，静态元素
控制层：可变化元素，可拖动旋转，鼠标显影
数据层：同时绑定上两层的数据
如果有这样的设计，那我就可以在anchor的展示层增加展示元素即可达到我的目标

**Comment by ananzhusen** [comment]
可以二开对绘制锚点的函数进行改造，meta2d.canvas.renderHoverPoint = ()=>{...},参考核心库renderHoverPoint 方法，目前的逻辑是只绘制hover锚点，改造成遍历所有图元，绘制图元的锚点。
