### ISSUE TITLE
[Bug]: 性能问题

### ISSUE THREAD

**Issue by Terrency** [le5le-com/meta2d.js#258]
### Code Sanbox异常重现

官网可复现

### bug描述

画布内添加很少的内容
使用右键移动画布，能够发现画布中的元素移动不连续，能够看到肉眼可见的卡顿
通过使用processon中添加元素，并右键移动画布进行对比就能很清晰的判断，确实为事件过多导致的性能问题，画布移动不连续，导致最终可视化效果不连续

### 期待效果

能够流畅的移动画布（无明显卡顿），和相关定量的性能分析结果

### 发生频率

每次

**Comment by ananzhusen** [comment]
烦请提供测试的图纸id，官方的解决方案图纸测试无卡顿现象,图纸id查看方式：
![image](https://github.com/user-attachments/assets/d5a4b1fd-ba1b-44ab-8124-6cd566016815)

**Comment by Terrency** [comment]
这个卡顿和平滑的视觉效果需要对比才能看得出来，我上传两张不同效果的gif动图，录制帧率为60hz，画布放到最大，相同的鼠标和浏览器环境，分别来源于官方画布绘制的带一个矩形图形和processon画布带有一个矩形的图像效果，您尝试看看能否看出来差异
![bbb](https://github.com/user-attachments/assets/6c4f80cf-d026-4e7f-9802-e5dcfb771fe7)
![ccc](https://github.com/user-attachments/assets/602ee4dc-8d06-4ca7-b4bf-8c8cf8e84f03)

**Comment by Grnetsky** [comment]
你可以通过设置meta2d的interval属性来设置图纸渲染帧率。官网是考虑到大多数用户机器的性能，而限制了其渲染帧率，默认为33.33hz。

对于你所说的和processon渲染效果有区别，原因是processon和meta2d的原理不同，processon采用的svg，meta2d基于canvas，对于少量图元来说，svg的性能可能会更好，对于大量图元来说，canvas性能肯定是大幅度优于svg的，因为svg的移动都会触发浏览器对于DOM的重排重绘。

另一方面，meta2d应用的场景不同，meta2d主要用于数字孪生，物联网等需要与大量数据大量图元和用户频繁交互的场景，所以在渲染前时核心库对于很多功能都需要去加载，计算，所以在js层面可能会浪费一定时间，与电脑性能和浏览器版本（不同版本对于v8引擎优化有所差异）有关。
