### ISSUE TITLE
[Bug]: 当画布放大，echarts图形会超出

### ISSUE THREAD

**Issue by heimayouzi** [le5le-com/meta2d.js#264]
### bug描述

当画布放大，echarts图形会超出画布
![50f3ccad-0ba9-4c0a-a0c9-1a26f8eef722](https://github.com/user-attachments/assets/da8a02ef-9cd7-4501-8f7f-e1c6d0c9a515)

### 期待效果

和其他基本图形一样，在画布范围内

### 发生频率

每次

**Comment by Grnetsky** [comment]
应该跟你的dom结构有关，这个echarts设置了z-index属性，你需要检测下你自己的dom结构是否合理，或者给对应的dom添加z-index属性

**Comment by heimayouzi** [comment]
没有，设置了zIndex是1的时候，还是会超出

**Comment by ananzhusen** [comment]
meta2d会有dom层级限制，可以设置图元zIndex属性，但是交互也会有影响
![image](https://github.com/user-attachments/assets/a2b932f6-bd15-42e0-990e-ab738332210e)
