### ISSUE TITLE
【缺陷】组合、旋转、放大有异常

### ISSUE THREAD

**Issue by wang11111** [le5le-com/meta2d.js#38]
原本效果
![e7fec4732677c268129b1d035a57eb9](https://user-images.githubusercontent.com/14358013/163781518-9aca9e56-0d8f-4d0d-aad1-f27de2e3d7b0.png)
组合旋转放大后效果
![fe8ee666780d5f14f9fa6319b314cdd](https://user-images.githubusercontent.com/14358013/163781594-1e73fb8b-40f8-4830-9b05-9b449d89602b.png)

**Comment by wang11111** [comment]
请问大佬是否考虑修改这个问题，最近几天梳理了一下这块，有点难下手

**Comment by ananzhusen** [comment]
建议组合后锁定宽高比
![image](https://github.com/user-attachments/assets/e7033336-c822-44f4-8437-54e92a68beb2)
