### ISSUE TITLE
保持比例对所有图形生效， 子保持比例，生成的父也保持比例。

### ISSUE THREAD

**Issue by SignDawn** [le5le-com/meta2d.js#48]
存在一个问题，对于图形而言，是可以设置图片的，那么只用一个 imageRatio 属性，是存在冲突的。考虑增加一个画笔的 保持比例属性！

**Comment by ananzhusen** [comment]
![image](https://github.com/le5le-com/meta2d.js/assets/48847159/d81ac6dc-0721-4172-8437-1f5114fdda09)

新增：锁定宽高比 对应ratio属性
