### ISSUE TITLE
【建议】添加节点生成方式

### ISSUE THREAD

**Issue by wang11111** [le5le-com/meta2d.js#61]

**Comment by SignDawn** [comment]
什么意思？不明白，具体些

**Comment by wang11111** [comment]
目前节点都是拖拽生成默认大小的节点，是否考虑，选择一个节点，鼠标在画布上选中一个区域，这个区域就是节点的大小和位置，和window的画图软件类似

**Comment by wang11111** [comment]
主要考虑拖拽出来的节点，大小和位置都需要再调整，特别在放大画布的时候，拖拽的节点也变大，对于绘制的场景，不太方便

**Comment by SignDawn** [comment]
老版本官网 http://topology.le5le.com/workspace/ 有这个功能。
点击左侧系统组件某一个，在画布上 dragRect ，就可以生成一个指定大小的。
但它也有问题，容易因为误操作，带来一个很小的图形

**Comment by wang11111** [comment]
可以有一个判断，小于一定的范围，就认为是误操作

**Comment by SignDawn** [comment]
@wang11111  老版本官网的这个功能，和你的意思是相同的吗？
误操作可以做，只是需要考虑这个功能是否有必要

**Comment by wang11111** [comment]
是这个意思

**Comment by wang11111** [comment]
个人认为在绘制组态这方面有帮助
