### ISSUE TITLE
请问可以设置画布大小吗  用户自定义画布大小

### ISSUE THREAD

**Issue by Blizzard-liu** [le5le-com/meta2d.js#71]

**Comment by SignDawn** [comment]
目前不考虑支持，没见过这种场景。

**Comment by Blizzard-liu** [comment]
我试了固定div的大小  配置 scroll: false,disableScale:true,disableTranslate:true
发现拖动元素到滚动条的位置 就拖不动了 还伴随其他问题 元素无法选择 画布出现红色的直线等

![image](https://user-images.githubusercontent.com/20244432/173003440-ab2650de-20d8-4ec5-80df-9b569bbaf23f.png)

**Comment by bici-fed** [comment]
> 请问你解决这个问题了吗？我也有这个需求？

我解决了这个问题，直接改的源码
