### ISSUE TITLE
置顶 置底画笔  移动画笔到上一层 下一层

### ISSUE THREAD

**Issue by Blizzard-liu** [le5le-com/meta2d.js#74]
![image](https://user-images.githubusercontent.com/20244432/174566453-79ff952f-d092-4891-847f-0cdbe829a899.png)
置顶 置底画笔  移动画笔到上一层 下一层 
第二个参数 使用传入的数组 无效

**Comment by Blizzard-liu** [comment]
![image](https://user-images.githubusercontent.com/20244432/174574771-f4c06458-8063-4d7e-92f9-9adec524c62f.png)

**Comment by Blizzard-liu** [comment]
大佬 这个bug都一个月了还没解决 很难搞吗

**Comment by SignDawn** [comment]
![6214602b082c5d80fbf3dad471796e4](https://user-images.githubusercontent.com/48878568/179766629-afc49914-91e4-4e5e-bf81-e1fba8807935.jpg)
不敢得瑟

**Comment by Blizzard-liu** [comment]
辣鸡  给你测试提bug 还这么拽  有本事bug都别改 我又不着急  心眼比鸡眼还小  滚回家种地吧

**Comment by SignDawn** [comment]
第二个参数暂时先不传，目前来看这么传不对。

**Comment by EightDoor** [comment]
提bug，人家愿意改，什么时候改，都是可以的吧。fork 一份要么就自己改，骂人就不对了吧

**Comment by Alsmile** [comment]
第二个参数将废除，因为传入一个随意的数组，这是的顺序没有任何意义（可以是任意的），与画布本身的顺序没有任何关联。
