### ISSUE TITLE
[bug]选择多个图元 ,上一个图层,下一个图层  的bug

### ISSUE THREAD

**Issue by Blizzard-liu** [le5le-com/meta2d.js#93]
![6](https://user-images.githubusercontent.com/20244432/179467464-c83eff5b-ed96-49e6-86f6-028766fd12e2.gif)

**Comment by SignDawn** [comment]
可以理解成每个图元都是一个单独的图层。
所以可能有会其他图元的干扰，导致上一个图层要点很多下才能在你想要的地方出现。
建议直接使用置顶，置底
