### ISSUE TITLE
[bug]组合之后 ,上一个图层,下一个图层  的bug

### ISSUE THREAD

**Issue by Blizzard-liu** [le5le-com/meta2d.js#94]
![5](https://user-images.githubusercontent.com/20244432/179467943-64dd576f-910a-4357-abc5-ba28f555e675.gif)

**Comment by SignDawn** [comment]
上下一个图层目前不支持组合节点。
建议直接使用置顶，置底

**Comment by Alsmile** [comment]
fixed
