### ISSUE TITLE
[建议] 取消默认的hoverColor

### ISSUE THREAD

**Issue by Blizzard-liu** [le5le-com/meta2d.js#95]
大部分情况下 是不需要设置hoverColor的 现在页面鼠标移过 都会触发hoverColor 感觉很不友好  如需要 可以单独设置

**Comment by Blizzard-liu** [comment]
编辑状态可以有hoverColor  预览状态取消默认的hoverColor

**Comment by Alsmile** [comment]
meta2d.setOptions({hoverColor: undefined})
